import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  Banknote,
  Box,
  Clock3,
  Gauge,
  MapPinned,
  Package,
  PackageCheck,
  Star,
  Timer,
  TrendingUp,
  Truck,
  Users,
  Wallet,
  Warehouse,
} from "lucide-react";
import type { UserRole } from "@/lib/auth/types";

export type MetricSentiment = "positive" | "negative";

export interface DashboardMetric {
  label: string;
  value: string;
  previousValue: string;
  changeLabel: string;
  changePercent: number;
  sentiment: MetricSentiment;
  hint: string;
  icon: LucideIcon;
}

export const ROLE_METRICS: Record<UserRole, DashboardMetric[]> = {
  SUPERADMIN: [
    {
      label: "Active merchants",
      value: "12",
      previousValue: "10",
      changeLabel: "vs last month",
      changePercent: 20,
      sentiment: "positive",
      hint: "Across all regions",
      icon: Users,
    },
    {
      label: "Fleet partners",
      value: "148",
      previousValue: "132",
      changeLabel: "vs last month",
      changePercent: 12.1,
      sentiment: "positive",
      hint: "Verified drivers",
      icon: Truck,
    },
    {
      label: "Open dispatches",
      value: "37",
      previousValue: "44",
      changeLabel: "vs last month",
      changePercent: -15.9,
      sentiment: "positive",
      hint: "Lower backlog is better",
      icon: Package,
    },
    {
      label: "Platform revenue",
      value: "Rp 4.2M",
      previousValue: "Rp 3.6M",
      changeLabel: "vs last month",
      changePercent: 16.7,
      sentiment: "positive",
      hint: "Month-to-date",
      icon: Banknote,
    },
  ],
  REGIONAL_MANAGER: [
    {
      label: "Jakarta SLA",
      value: "96.4%",
      previousValue: "94.8%",
      changeLabel: "vs last month",
      changePercent: 1.7,
      sentiment: "positive",
      hint: "Last 24 hours",
      icon: Gauge,
    },
    {
      label: "Active hubs",
      value: "8",
      previousValue: "7",
      changeLabel: "vs last month",
      changePercent: 14.3,
      sentiment: "positive",
      hint: "Operational",
      icon: MapPinned,
    },
    {
      label: "Escalations",
      value: "3",
      previousValue: "6",
      changeLabel: "vs last month",
      changePercent: -50,
      sentiment: "positive",
      hint: "Needs review",
      icon: AlertTriangle,
    },
    {
      label: "Fleet utilization",
      value: "78%",
      previousValue: "72%",
      changeLabel: "vs last month",
      changePercent: 8.3,
      sentiment: "positive",
      hint: "Peak window",
      icon: TrendingUp,
    },
  ],
  HEAD_OF_WAREHOUSE: [
    {
      label: "Inbound staging",
      value: "24",
      previousValue: "31",
      changeLabel: "vs last month",
      changePercent: -22.6,
      sentiment: "positive",
      hint: "Parcels ready",
      icon: Box,
    },
    {
      label: "Dock capacity",
      value: "62%",
      previousValue: "71%",
      changeLabel: "vs last month",
      changePercent: -12.7,
      sentiment: "positive",
      hint: "Central hub",
      icon: Warehouse,
    },
    {
      label: "Cancellations",
      value: "2",
      previousValue: "5",
      changeLabel: "vs last month",
      changePercent: -60,
      sentiment: "positive",
      hint: "Today",
      icon: AlertTriangle,
    },
    {
      label: "Handoff SLA",
      value: "18 min",
      previousValue: "24 min",
      changeLabel: "vs last month",
      changePercent: -25,
      sentiment: "positive",
      hint: "Avg pickup wait",
      icon: Clock3,
    },
  ],
  FLEET_OPERATOR: [
    {
      label: "BullMQ jobs",
      value: "14",
      previousValue: "22",
      changeLabel: "vs last month",
      changePercent: -36.4,
      sentiment: "positive",
      hint: "dispatch-queue",
      icon: Timer,
    },
    {
      label: "Online drivers",
      value: "41",
      previousValue: "36",
      changeLabel: "vs last month",
      changePercent: 13.9,
      sentiment: "positive",
      hint: "Within 10 km radius",
      icon: Users,
    },
    {
      label: "Unassigned",
      value: "6",
      previousValue: "11",
      changeLabel: "vs last month",
      changePercent: -45.5,
      sentiment: "positive",
      hint: "Pending match",
      icon: Package,
    },
    {
      label: "Avg match time",
      value: "42s",
      previousValue: "58s",
      changeLabel: "vs last month",
      changePercent: -27.6,
      sentiment: "positive",
      hint: "Haversine pool",
      icon: Gauge,
    },
  ],
  MERCHANT_ADMIN: [
    {
      label: "Today's orders",
      value: "9",
      previousValue: "7",
      changeLabel: "vs last month avg",
      changePercent: 28.6,
      sentiment: "positive",
      hint: "Acme Commerce",
      icon: Package,
    },
    {
      label: "In transit",
      value: "4",
      previousValue: "6",
      changeLabel: "vs last month avg",
      changePercent: -33.3,
      sentiment: "positive",
      hint: "Active deliveries",
      icon: Truck,
    },
    {
      label: "Wallet balance",
      value: "Rp 2.1M",
      previousValue: "Rp 1.8M",
      changeLabel: "vs last month",
      changePercent: 16.7,
      sentiment: "positive",
      hint: "Prepaid ledger",
      icon: Wallet,
    },
    {
      label: "Success rate",
      value: "98.1%",
      previousValue: "96.4%",
      changeLabel: "vs last month",
      changePercent: 1.8,
      sentiment: "positive",
      hint: "Last 7 days",
      icon: PackageCheck,
    },
  ],
  DRIVER_PARTNER: [
    {
      label: "Assigned jobs",
      value: "2",
      previousValue: "3",
      changeLabel: "vs last month avg",
      changePercent: -33.3,
      sentiment: "negative",
      hint: "Your queue",
      icon: Package,
    },
    {
      label: "Completed today",
      value: "5",
      previousValue: "4",
      changeLabel: "vs last month avg",
      changePercent: 25,
      sentiment: "positive",
      hint: "Proof of delivery",
      icon: PackageCheck,
    },
    {
      label: "Earnings",
      value: "Rp 285K",
      previousValue: "Rp 240K",
      changeLabel: "vs last month",
      changePercent: 18.8,
      sentiment: "positive",
      hint: "90% payout share",
      icon: Banknote,
    },
    {
      label: "Rating",
      value: "4.9",
      previousValue: "4.8",
      changeLabel: "vs last month",
      changePercent: 2.1,
      sentiment: "positive",
      hint: "Partner score",
      icon: Star,
    },
  ],
};
